### ISSUE TITLE
How to get all options?

### ISSUE THREAD

**Issue by daolou** [cacjs/cac#136]
## Issue Type

- [ ] Bug Report
- [X] Feature Request
- [ ] Other

## Expected

I want to wrap git:

1. index.js
![image](https://user-images.githubusercontent.com/22312092/161223921-7003e117-7043-42f7-83ca-8eef8d375ac3.png)

```js
cli.command('git [...commands]', '执行 git 批量操作')
  .action((commands, options) => {
    console.log(commands);
    console.log(options);
  });
```
3. use
```sh
node index.js git tag -a v1.0.0 -m 'feat 1.0.0'
```

Expect the options( `-a`,`-m`) could log in line "`console.log(options);`"

## Actual

![image](https://user-images.githubusercontent.com/22312092/161223951-a2ea0d2e-d39f-4ce6-a505-b15beb0135eb.png)

```sh
throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
CACError: Unknown option `-a`
    at Command.checkUnknownOptions (/Users/jzg/Workspace/oko/node_modules/_cac@6.7.11@cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/Users/jzg/Workspace/oko/node_modules/_cac@6.7.11@cac/dist/index.js:602:13)
    at CAC.parse (/Users/jzg/Workspace/oko/node_modules/_cac@6.7.11@cac/dist/index.js:541:12)
    at CLI (/Users/jzg/Workspace/oko/lib/utils/cac.js:39:7)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Info

- CAC version: 6.7.11
- Reproduction link:  https://replit.com/@daolou/cac-playground#index.js

**Comment by egoist** [comment]
by default it only allows known options added by `cli.option`: https://github.com/cacjs/cac#clioptionname-description-config

or `.allowUnknownOptions` if that's what you want: https://github.com/cacjs/cac#commandallowunknownoptions
